module.exports = {
  REQUIRED_EMAIL: 'Email is required!',
  REQUIRED_FIRSTNAME: 'Firstname is required!',
  REQUIRED_LASTNAME: 'Lastname is required!',
  REQUIRED_PASSWORD: 'Password is required!',
  REQUIRED_USERNAME: 'Username is required!',
  LENGTH_PASSWORD: 'Password need to be longer!',
  VALID_CUSTOM: 'is not valid',
  ERROR_USEREXISTS: 'User already exists!',
  ERROR_USERNOTFOUND: 'User is not found!',
  REQUIRED_TITLE: 'Title is required!',
  REQUIRED_SLUG: 'Slug is required!',
  ERROR_SAMETITLEORSLUG: 'Title or slug are same!',
  ERROR_PASSWORD: 'Incorrect password!',
  ERROR_EMAIL: 'Incorrect email!',
  SUCCESSFUL_LOGIN: 'Sign In successfully!',
  ERROR_NOTACCESSIBLE: 'You do not have access to this resource!',
};
